# Generated by Django 4.2.30 on 2026-09-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestedfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('awaiting_further_processing', 'Awaiting further processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=32),
        ),
    ]
