# Generated by Django 4.2.30 on 2026-10-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_alter_ingestedfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestedfile',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestedfile',
            name='reclaimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
