# Generated by Django 4.2.30 on 2026-09-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('sensors', '0003_country_sensor_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=32)),
                ('rayhunter_version', models.CharField(blank=True, max_length=50)),
                ('system_os', models.CharField(blank=True, max_length=100)),
                ('arch', models.CharField(blank=True, max_length=50)),
                ('report_version', models.IntegerField(blank=True, null=True)),
                ('analyzers', models.JSONField(blank=True, default=list)),
                ('has_gps', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('general_log_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ingestion.ingestedfile')),
                ('gps_log_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ingestion.ingestedfile')),
                ('qmdl_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ingestion.ingestedfile')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_sessions', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sensor', 'session_id')},
            },
        ),
        migrations.CreateModel(
            name='RayhunterLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('qmdl_timestamp', models.DateTimeField(blank=True, null=True)),
                ('gps_timestamp', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_alert', models.BooleanField(default=False)),
                ('severity', models.CharField(blank=True, choices=[('Informational', 'Informational'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('log_entry', models.TextField(blank=True)),
                ('raw_payload', models.JSONField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rayhunter_log_entries', to='sensors.sensor')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='captures.monitoringsession')),
            ],
            options={
                'ordering': ['session', 'line_number'],
                'indexes': [models.Index(fields=['sensor', 'qmdl_timestamp'], name='captures_ra_sensor__d24421_idx'), models.Index(fields=['sensor', 'is_alert'], name='captures_ra_sensor__4be2aa_idx')],
            },
        ),
    ]
